---
grails:
    profile: angularjs
    codegen:
        defaultPackage: org.modelcatalogue.core
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities.
        # Disabled by default for performance reasons.
        autowire: false
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    resources:
        pattern: /**
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json
            hal:
              - application/hal+json
              - application/hal+xml
#            xml:
#              - text/xml
#              - application/xml
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            multipartForm: multipart/form-data
            xsl: text/xsl
            xlsx:
                - application/vnd.ms-excel
                - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
            all: '*/*'
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    databinding:
        dateFormats:
            - MMddyyyy
            - yyyy-MM-dd HH:mm:ss.S
            - yyyy-MM-dd'T'hh:mm:sss'Z'
    exceptionresolver:
        params:
            exclude:
                - password
                - password1
                - password2
                - client_secret
    views:
        gsp:
            codecs:
                scriptlet: html #escapes output from scriptlets in GSPs

---
hibernate:
    format_sql: true
    use_sql_comments: true
    generate_statistics: true
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
#        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    jmxExport: true

environments:
    development:
        dataSource:
            pooled: true
            dbCreate: create-drop
            driverClassName: org.h2.Driver
            username: sa
            password: ''
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

---
grails:
    plugin:
        springsecurity:
            oauth:
                domainClass: org.modelcatalogue.core.security.OAuthID # Added by the Spring Security OAuth plugin
            userLookup:
                userDomainClassName: org.modelcatalogue.core.security.User
                authorityJoinClassName: org.modelcatalogue.core.security.UserRole
            authority:
                className: org.modelcatalogue.core.security.Role
            requestMap:
                className: org.modelcatalogue.core.testapp.Requestmap
            securityConfigType: Requestmap
            useBasicAuth: true
            basic:
                realmName: 'Model Catalogue'
            filterChain:
                chainMap:
                    -
                        pattern: /catalogue/upload
                        filters: 'JOINED_FILTERS,-exceptionTranslationFilter'
                    -
                        pattern: /catalogue/*/*/export
                        filters: 'JOINED_FILTERS,-exceptionTranslationFilter'
                    -
                        pattern: /user/current
                        filters: 'JOINED_FILTERS,-exceptionTranslationFilter'
                    -
                        pattern: '/api/modelCatalogue/core/feedback/**'
                        filters: 'JOINED_FILTERS,-exceptionTranslationFilter'
                    -
                        pattern: '/**'
                        filters: 'JOINED_FILTERS,-basicAuthenticationFilter,-basicExceptionTranslationFilter'
            logout:
                handlerNames:
                    - rememberMeServices
                    - securityContextLogoutHandler
                    - modelCatalogueSecurityService # both spring security services implements it
---
javamelody:
    # filter out numbers from URI
    http-transform-pattern: \d+
    displayed-counters: 'http,sql,error,log,spring,jsp'
    url-exclude-pattern: '/assets/.*|.*/download.*|.*/gereportDoc.*|.*/changelogDoc.*'
    disabled: true
environments:
    production:
        javamelody:
            disabled: false
---
environments:
    development:
        mc:
            allow:
                signup: true
            preload:
                -
                    name: 'Java Basic Types'
                    url: https://s3-eu-west-1.amazonaws.com/datamodels.metadata.org.uk/Java.mc.xml
    test:
        mc:
            allow:
                signup: true
    production:
        # you can overrides in your mc-config.groovy
        mc:
            sync:
                relationshipTypes: true
            storage: # configure the default storage
               directory: /tmp/mc/storage
               maxSize: 52428800 # 50 * 1024 * 1024
---
grails:
    plugin:
        springsecurity:
            ui:
                register:
                   defaultRoleNames: [] # no roles
--- # Spring Security Core - Debug Filter
environments:
    development:
        grails:
            logging:
                jul:
                    usebridge: true
    test:
        grails:
            logging:
                jul:
                    usebridge: true
    production:
        grails:
            logging:
                jul:
                    usebridge: false
--- # Grails Console
environments:
    development:
        grails:
            plugin:
                console:
                    enabled: true
    test:
        grails:
            plugin:
                console:
                    enabled: true
    production:
        grails:
            plugin:
                console:
                    enabled: false
---
beans:
    apiLegacyInterceptor:
        order: 50
    apiExpiresInterceptor:
        order: 60
    modelCatalogueIDInterceptor:
        order: 70
    springOAuthAjaxFixInterceptor:
        order: 80
---
environments:
    development:
        grails:
            mail:
                disabled: true
---
environments:
    development:
        oauth:
            providers:
                google:
                    # this key is limited to localhost only so no need to hide it
                    api: org.modelcatalogue.repack.org.scribe.builder.api.GoogleApi20
                    key: 225917730237-0hg6u55rgnld9cbtm949ab9h9fk5onr3.apps.googleusercontent.com
                    secret: OG0JVVoy4bnGm48bneIS0haB
                    successUri: /oauth/google/success
                    failureUri: /oauth/google/error
                    scope: 'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email'
    test:
        oauth:
            providers:
                google:
                    # this key is limited to localhost only so no need to hide it
                    api: org.modelcatalogue.repack.org.scribe.builder.api.GoogleApi20
                    key: 225917730237-0hg6u55rgnld9cbtm949ab9h9fk5onr3.apps.googleusercontent.com
                    secret: OG0JVVoy4bnGm48bneIS0haB
                    successUri: /oauth/google/success
                    failureUri: /oauth/google/error
                    scope: 'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email'
---
grails:
    assets:
        babel:
            enabled: true
#---
#environments:
#    development:
#        discourse:
#            url: http://192.168.1.123/
#            api:
#                key: af9402ba45b8f4aff5a84bcdf6da85fc7548db746026c5095ed652d0f83fcd8b
#                user: discourse
#            users:
#                fallbackEmail: vladimir.orany+:username@gmail.com
#            sso:
#                key: System.getenv('METADATA_DISCOURSE_SSO_KEY') ?: "notasecret"
---
environments:
    development:
        grails:
            serverURL: http://localhost:8080
